# Generated by Django 4.0.10 on 2023-04-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_search_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
