# Generated by Django 4.0.10 on 2023-04-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_search_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
