# Generated by Django 4.0.10 on 2023-04-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_weatherdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='weather',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='data',
            field=models.TextField(),
        ),
    ]
