# Generated by Django 4.0.10 on 2023-04-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_usersearch_id_alter_usersearch_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearch',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersearch',
            name='user_id',
            field=models.CharField(max_length=100),
        ),
    ]
