# Generated by Django 4.0.10 on 2023-04-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_usersearch_id_alter_usersearch_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('send_time', models.DateTimeField()),
            ],
        ),
    ]
