# Generated by Django 4.0.10 on 2023-04-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSearch',
        ),
    ]
