# Generated by Django 4.0.10 on 2023-04-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_delete_usersearch'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('send_time', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('current_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
